export ZSH="/home/ivo/.oh-my-zsh"

ZSH_THEME="spaceship"

autoload bashcompinit
bashcompinit

plugins=(
  fzf
)

source ~/.oh-my-zsh/plugins/git/git.plugin.zsh
source $ZSH/oh-my-zsh.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Edit command in vim
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

## Hub related
alias g="hub"
alias cleanvim='vi -u ~/.vimrc.sample'

## Git related
alias gm='git commit'
alias gs='git status'
alias ga='git add'
alias gap='git add -p'
alias gup='git pull origin $(git rev-parse --abbrev-ref HEAD)'
alias gprsdiff='/home/ivo/Code/dotfiles/scripts/prs_diff.sh'

## Yarn related
alias yas='yarn start'
alias yat='yarn test'

## Python related
alias py="python3"
#
# Pyenv related
export PYENV_VIRTUALENV_DISABLE_PROMPT=1

## Django related
alias pmr='python3 manage.py runserver'
alias pmm='python manage.py migrate'
alias pmmm='python manage.py makemigrations'
alias pms='python manage.py shell'
alias pmsp='python manage.py shell_plus'


alias explorer='nautilus --browser'
alias g='hub';
alias dbshell='sudo su postgres -c "psql"'

alias keychron-fn-keys='echo 0 | sudo tee /sys/module/hid_apple/parameters/fnmode'

# Pyenv settings
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
   eval "$(pyenv init -)"
fi

alias files-count='ls -1 | wc -l'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Theme settings
SPACESHIP_CHAR_SYMBOL="❯ "
SPACESHIP_HG_SHOW="false"
SPACESHIP_HG_BRANCH_SHOW="false"
SPACESHIP_HG_STATUS_SHOW="false"
SPACESHIP_PACKAGE_SHOW="false"
SPACESHIP_RUBY_SHOW="false"
SPACESHIP_ELIXIR_SHOW="false"
SPACESHIP_XCODE_SHOW_LOCAL="false"
SPACESHIP_SWIFT_SHOW_LOCAL="false"
SPACESHIP_GOLANG_SHOW="false"
SPACESHIP_PHP_SHOW="false"
SPACESHIP_RUST_SHOW="false"
SPACESHIP_HASKELL_SHOW="false"
SPACESHIP_JULIA_SHOW="false"
SPACESHIP_DOCKER_SHOW="false"
SPACESHIP_AWS_SHOW="false"
SPACESHIP_VENV_SHOW="true"
SPACESHIP_PYENV_SHOW="false"
SPACESHIP_VENV_PREFIX="using "
SPACESHIP_DOTNET_SHOW="false"
SPACESHIP_EMBER_SHOW="false"
SPACESHIP_KUBECONTEXT_SHOW="false"
SPACESHIP_GIT_STATUS_SHOW="false"

export ANDROID_HOME=/opt/android

source $(dirname $(gem which colorls))/tab_complete.sh  # https://github.com/athityakumar/colorls
alias ls='colorls'

eval "$(jump shell)"


source "/home/ivo/.oh-my-zsh/custom/themes/spaceship.zsh-theme"

. "$HOME/.cargo/env"


